/**
 * Core Lifecycle 100 — master scenario matrix linking quotation → payment → cutting list
 * → production → stock → refund as one interconnected test chain.
 *
 * Types: smoke | e2e | integration | crash | fraud | financial | inventory
 * Run: npm run test:lifecycle100
 */

/** @typedef {'quotation'|'payment'|'cutting_list'|'production'|'stock'|'refund'|'delivery'|'auth'} ModuleKey */
/** @typedef {'smoke'|'e2e'|'integration'|'crash'|'fraud'|'financial'|'inventory'} ScenarioType */

/**
 * @typedef {Object} LifecycleScenario
 * @property {string} id
 * @property {string} title
 * @property {ModuleKey[]} modules
 * @property {ScenarioType} type
 * @property {string|null} prevId — previous scenario in the chain
 * @property {string|null} nextId — next scenario in the chain
 * @property {string[]} riskTags — fraud | hack | financial_failure | inventory_gap | dual_control | branch_scope
 * @property {{ kind: 'vitest', file: string, anchor?: string } | { kind: 'e2e', spec: string, grep?: string } | { kind: 'inline' }} runner
 * @property {string} [mapsTo] — existing scenario id (SCN-xxx, TX-xx, S1, RFS-xxx, FIN-Fxxx)
 */

/** @type {LifecycleScenario[]} */
export const CORE_LIFECYCLE_100 = [
  // ── SMOKE (001–010): golden paths, full chain anchors ─────────────────────
  {
    id: 'LC100-001',
    title: 'Customer create → quotation Pending with correct total',
    modules: ['quotation'],
    type: 'smoke',
    prevId: null,
    nextId: 'LC100-002',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: '1. Customer creation' },
    mapsTo: 'TX-01',
  },
  {
    id: 'LC100-002',
    title: 'Quotation totals and Pending status for new customer',
    modules: ['quotation'],
    type: 'smoke',
    prevId: 'LC100-001',
    nextId: 'LC100-003',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: '2. Quotation for new customer' },
    mapsTo: 'TX-02',
  },
  {
    id: 'LC100-003',
    title: 'Full receipt clears quotation balance (quote → payment)',
    modules: ['quotation', 'payment'],
    type: 'smoke',
    prevId: 'LC100-002',
    nextId: 'LC100-004',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: '3. Full payment' },
    mapsTo: 'TX-03',
  },
  {
    id: 'LC100-004',
    title: 'Cutting list from paid quote — metre totals match',
    modules: ['quotation', 'payment', 'cutting_list'],
    type: 'smoke',
    prevId: 'LC100-003',
    nextId: 'LC100-005',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-001' },
    mapsTo: 'SCN-001',
  },
  {
    id: 'LC100-005',
    title: 'Small flatsheet cutting list (10m)',
    modules: ['quotation', 'cutting_list'],
    type: 'smoke',
    prevId: 'LC100-004',
    nextId: 'LC100-006',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-002' },
    mapsTo: 'SCN-002',
  },
  {
    id: 'LC100-006',
    title: 'Split tender receipt (cash + POS + transfer)',
    modules: ['payment'],
    type: 'smoke',
    prevId: 'LC100-005',
    nextId: 'LC100-007',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-003' },
    mapsTo: 'SCN-003',
  },
  {
    id: 'LC100-007',
    title: 'Advance deposit then apply to final quotation',
    modules: ['payment', 'quotation'],
    type: 'smoke',
    prevId: 'LC100-006',
    nextId: 'LC100-008',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-005' },
    mapsTo: 'SCN-005',
  },
  {
    id: 'LC100-008',
    title: 'Full lifecycle: quote → pay → cut → production register',
    modules: ['quotation', 'payment', 'cutting_list', 'production'],
    type: 'smoke',
    prevId: 'LC100-007',
    nextId: 'LC100-009',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'cutting list' },
    mapsTo: 'TX-08',
  },
  {
    id: 'LC100-009',
    title: 'Overpay → cutting → production → refund payout',
    modules: ['quotation', 'payment', 'cutting_list', 'production', 'refund'],
    type: 'smoke',
    prevId: 'LC100-008',
    nextId: 'LC100-010',
    riskTags: ['financial_failure', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-006' },
    mapsTo: 'SCN-006',
  },
  {
    id: 'LC100-010',
    title: 'E2E UI: Sales → Operations → Finance navigation smoke',
    modules: ['quotation', 'payment', 'production', 'stock'],
    type: 'e2e',
    prevId: 'LC100-009',
    nextId: 'LC100-011',
    riskTags: [],
    runner: { kind: 'e2e', spec: 'e2e/core-lifecycle100-smoke.spec.js', grep: 'module chain' },
  },

  // ── QUOTATION (011–020) ───────────────────────────────────────────────────
  {
    id: 'LC100-011',
    title: 'Quotation expiry after 10 days without commitment',
    modules: ['quotation'],
    type: 'integration',
    prevId: 'LC100-010',
    nextId: 'LC100-012',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/quotationLifecycleOps.test.js' },
    mapsTo: 'Q-LIFE-EXP',
  },
  {
    id: 'LC100-012',
    title: 'Payment commitment blocks quotation expiry',
    modules: ['quotation', 'payment'],
    type: 'integration',
    prevId: 'LC100-011',
    nextId: 'LC100-013',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/quotationLifecycleOps.test.js' },
  },
  {
    id: 'LC100-013',
    title: 'Revive expired quotation after manager clearance',
    modules: ['quotation'],
    type: 'integration',
    prevId: 'LC100-012',
    nextId: 'LC100-014',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'revive' },
    mapsTo: 'TX-14',
  },
  {
    id: 'LC100-014',
    title: 'Void quotation with no production commitment',
    modules: ['quotation'],
    type: 'integration',
    prevId: 'LC100-013',
    nextId: 'LC100-015',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'Void' },
  },
  {
    id: 'LC100-015',
    title: 'MD price exception below floor',
    modules: ['quotation'],
    type: 'integration',
    prevId: 'LC100-014',
    nextId: 'LC100-016',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/reviewQuotation.test.js' },
  },
  {
    id: 'LC100-016',
    title: 'Quotation recalc after line edit',
    modules: ['quotation'],
    type: 'integration',
    prevId: 'LC100-015',
    nextId: 'LC100-017',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/quotationRecalcOrchestrator.test.js' },
  },
  {
    id: 'LC100-017',
    title: 'Refunds blocked flag on quotation',
    modules: ['quotation', 'refund'],
    type: 'integration',
    prevId: 'LC100-016',
    nextId: 'LC100-018',
    riskTags: ['fraud', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/quotationRefundsBlocked.test.js' },
  },
  {
    id: 'LC100-018',
    title: 'Staff purchase credit link on quotation',
    modules: ['quotation', 'payment'],
    type: 'integration',
    prevId: 'LC100-017',
    nextId: 'LC100-019',
    riskTags: ['fraud'],
    runner: { kind: 'vitest', file: 'server/staffPurchaseCreditLink.test.js' },
  },
  {
    id: 'LC100-019',
    title: 'Credit exception allows delivery without full pay',
    modules: ['quotation', 'payment', 'delivery'],
    type: 'integration',
    prevId: 'LC100-018',
    nextId: 'LC100-020',
    riskTags: ['financial_failure', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/creditExceptionOps.test.js' },
  },
  {
    id: 'LC100-020',
    title: 'Quotation payment integrity sync from ledger',
    modules: ['quotation', 'payment'],
    type: 'integration',
    prevId: 'LC100-019',
    nextId: 'LC100-021',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/quotationPaymentIntegrity.test.js' },
  },

  // ── PAYMENT (021–035) ─────────────────────────────────────────────────────
  {
    id: 'LC100-021',
    title: 'Underpayment leaves exact outstanding balance',
    modules: ['payment', 'quotation'],
    type: 'financial',
    prevId: 'LC100-020',
    nextId: 'LC100-022',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-004' },
    mapsTo: 'SCN-004',
  },
  {
    id: 'LC100-022',
    title: '99.5% tolerance treats near-full pay as Paid',
    modules: ['payment', 'quotation'],
    type: 'financial',
    prevId: 'LC100-021',
    nextId: 'LC100-023',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'shared/lib/customerLedgerCore.test.js' },
  },
  {
    id: 'LC100-023',
    title: 'Overpayment creates advance credit pool',
    modules: ['payment'],
    type: 'financial',
    prevId: 'LC100-022',
    nextId: 'LC100-024',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'overpay' },
  },
  {
    id: 'LC100-024',
    title: 'Auto overpay apply to next quotation',
    modules: ['payment', 'quotation'],
    type: 'financial',
    prevId: 'LC100-023',
    nextId: 'LC100-025',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/customerPaymentIntegrity.test.js' },
  },
  {
    id: 'LC100-025',
    title: 'Receipt reversal restores quotation balance',
    modules: ['payment', 'quotation'],
    type: 'financial',
    prevId: 'LC100-024',
    nextId: 'LC100-026',
    riskTags: ['financial_failure', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'reverse' },
  },
  {
    id: 'LC100-026',
    title: 'Advance reversal restores customer advance balance',
    modules: ['payment'],
    type: 'financial',
    prevId: 'LC100-025',
    nextId: 'LC100-027',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'advance' },
  },
  {
    id: 'LC100-027',
    title: 'Duplicate receipt detection with override reason',
    modules: ['payment'],
    type: 'fraud',
    prevId: 'LC100-026',
    nextId: 'LC100-028',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/receiptPostingGuards.test.js' },
  },
  {
    id: 'LC100-028',
    title: 'Period lock blocks backdated receipt posting',
    modules: ['payment'],
    type: 'fraud',
    prevId: 'LC100-027',
    nextId: 'LC100-029',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-029',
    title: 'Delivery payment gate blocks unpaid dispatch',
    modules: ['payment', 'delivery'],
    type: 'financial',
    prevId: 'LC100-028',
    nextId: 'LC100-030',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/deliveryReleaseGate.test.js' },
  },
  {
    id: 'LC100-030',
    title: 'Cashier receipt clearance workflow (Pending → Cleared)',
    modules: ['payment'],
    type: 'integration',
    prevId: 'LC100-029',
    nextId: 'LC100-031',
    riskTags: ['dual_control'],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'clearance' },
  },
  {
    id: 'LC100-031',
    title: 'Split receipt across 2 treasury accounts',
    modules: ['payment'],
    type: 'integration',
    prevId: 'LC100-030',
    nextId: 'LC100-032',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-007' },
    mapsTo: 'SCN-007',
  },
  {
    id: 'LC100-032',
    title: 'Returning customer overpay on second quote',
    modules: ['payment', 'quotation'],
    type: 'integration',
    prevId: 'LC100-031',
    nextId: 'LC100-033',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'overpay scenario' },
  },
  {
    id: 'LC100-033',
    title: 'Returning customer underpay on second quote',
    modules: ['payment', 'quotation'],
    type: 'integration',
    prevId: 'LC100-032',
    nextId: 'LC100-034',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'underpay scenario' },
  },
  {
    id: 'LC100-034',
    title: 'Advance deposit partial apply leaves remainder',
    modules: ['payment', 'quotation'],
    type: 'integration',
    prevId: 'LC100-033',
    nextId: 'LC100-035',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'Advance deposit' },
  },
  {
    id: 'LC100-035',
    title: 'FIN100 stress: 100 live finance scenario batch',
    modules: ['payment', 'refund'],
    type: 'crash',
    prevId: 'LC100-034',
    nextId: 'LC100-036',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'scripts/data/hundredFinanceScenarios.mjs' },
    mapsTo: 'FIN-F000–F099',
  },

  // ── CUTTING LIST (036–050) ────────────────────────────────────────────────
  {
    id: 'LC100-036',
    title: '70% payment gate blocks cutting list finalize',
    modules: ['cutting_list', 'payment', 'quotation'],
    type: 'financial',
    prevId: 'LC100-035',
    nextId: 'LC100-037',
    riskTags: ['financial_failure', 'fraud'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-037',
    title: 'Cutting list metre alignment with quotation',
    modules: ['cutting_list', 'quotation'],
    type: 'integration',
    prevId: 'LC100-036',
    nextId: 'LC100-038',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/cuttingListDraftFinalize.test.js' },
  },
  {
    id: 'LC100-038',
    title: 'One non-draft cutting list per quotation enforced',
    modules: ['cutting_list', 'quotation'],
    type: 'integration',
    prevId: 'LC100-037',
    nextId: 'LC100-039',
    riskTags: ['fraud'],
    runner: { kind: 'vitest', file: 'server/cuttingListDraftFinalize.test.js' },
  },
  {
    id: 'LC100-039',
    title: 'Cutting list register production links job',
    modules: ['cutting_list', 'production'],
    type: 'integration',
    prevId: 'LC100-038',
    nextId: 'LC100-040',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'Cutting list registration' },
  },
  {
    id: 'LC100-040',
    title: 'Cutting list print audit trail',
    modules: ['cutting_list'],
    type: 'integration',
    prevId: 'LC100-039',
    nextId: 'LC100-041',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/cuttingListPrint.test.js' },
  },
  {
    id: 'LC100-041',
    title: 'Blank consumption reconciliation vs quote metres',
    modules: ['cutting_list', 'quotation', 'refund'],
    type: 'inventory',
    prevId: 'LC100-040',
    nextId: 'LC100-042',
    riskTags: ['inventory_gap', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/cuttingListQuotationConsumptionOps.test.js' },
  },
  {
    id: 'LC100-042',
    title: 'Refund blocks production on quotation',
    modules: ['cutting_list', 'production', 'refund'],
    type: 'fraud',
    prevId: 'LC100-041',
    nextId: 'LC100-043',
    riskTags: ['fraud', 'dual_control'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-043',
    title: 'Post-production cutting list edit requires approval',
    modules: ['cutting_list', 'production'],
    type: 'fraud',
    prevId: 'LC100-042',
    nextId: 'LC100-044',
    riskTags: ['fraud', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/cuttingListProductionGate.test.js' },
  },
  {
    id: 'LC100-044',
    title: 'Zero-payment production needs MD approval',
    modules: ['cutting_list', 'production', 'payment'],
    type: 'fraud',
    prevId: 'LC100-043',
    nextId: 'LC100-045',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/productionGateAccess.test.js' },
  },
  {
    id: 'LC100-045',
    title: '50-length roof order 1245.4m cutting list',
    modules: ['cutting_list', 'quotation'],
    type: 'crash',
    prevId: 'LC100-044',
    nextId: 'LC100-046',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-001' },
    mapsTo: 'SCN-001',
  },
  {
    id: 'LC100-046',
    title: 'Randomized cutting lists (5–20 lines, 80–1500m)',
    modules: ['cutting_list', 'production'],
    type: 'crash',
    prevId: 'LC100-045',
    nextId: 'LC100-047',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'Cutting list registration' },
  },
  {
    id: 'LC100-047',
    title: '27 micro lines totaling 3.33 meters (harsh)',
    modules: ['cutting_list'],
    type: 'crash',
    prevId: 'LC100-046',
    nextId: 'LC100-048',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-HARSH-08' },
    mapsTo: 'SCN-HARSH-08',
  },
  {
    id: 'LC100-048',
    title: 'Cutting list material readiness panel (UI)',
    modules: ['cutting_list', 'stock'],
    type: 'e2e',
    prevId: 'LC100-047',
    nextId: 'LC100-049',
    riskTags: ['inventory_gap'],
    runner: { kind: 'e2e', spec: 'e2e/core-lifecycle100-smoke.spec.js', grep: 'cutting list' },
  },
  {
    id: 'LC100-049',
    title: 'Clear production hold on cutting list',
    modules: ['cutting_list', 'production'],
    type: 'integration',
    prevId: 'LC100-048',
    nextId: 'LC100-050',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/transactionalScenarios.test.js', anchor: 'production hold' },
  },
  {
    id: 'LC100-050',
    title: 'Cutting list status flow Draft → Waiting → In production',
    modules: ['cutting_list', 'production'],
    type: 'integration',
    prevId: 'LC100-049',
    nextId: 'LC100-051',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/productionTraceability.test.js' },
  },

  // ── PRODUCTION (051–065) ──────────────────────────────────────────────────
  {
    id: 'LC100-051',
    title: 'Production job Planned → Running → Completed',
    modules: ['production'],
    type: 'smoke',
    prevId: 'LC100-050',
    nextId: 'LC100-052',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/productionTraceability.test.js' },
  },
  {
    id: 'LC100-052',
    title: 'Multi-coil allocation + conversion preview',
    modules: ['production', 'stock'],
    type: 'integration',
    prevId: 'LC100-051',
    nextId: 'LC100-053',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-VAL-01' },
    mapsTo: 'SCN-VAL-01',
  },
  {
    id: 'LC100-053',
    title: 'Single coil serves two production jobs',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-052',
    nextId: 'LC100-054',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-VAL-02' },
    mapsTo: 'SCN-VAL-02',
  },
  {
    id: 'LC100-054',
    title: 'Production start blocked without coil allocation',
    modules: ['production', 'stock'],
    type: 'fraud',
    prevId: 'LC100-053',
    nextId: 'LC100-055',
    riskTags: ['fraud', 'inventory_gap'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-055',
    title: 'Coil reservation integrity on job start',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-054',
    nextId: 'LC100-056',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/productionCoilReservation.test.js' },
  },
  {
    id: 'LC100-056',
    title: 'Conversion alert HIGH/LOW manager sign-off',
    modules: ['production'],
    type: 'integration',
    prevId: 'LC100-055',
    nextId: 'LC100-057',
    riskTags: ['inventory_gap', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/productionJobCoilIntegrity.test.js' },
  },
  {
    id: 'LC100-057',
    title: 'Production complete draws coil kg and updates stock',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-056',
    nextId: 'LC100-058',
    riskTags: ['inventory_gap', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S2' },
    mapsTo: 'S2',
  },
  {
    id: 'LC100-058',
    title: 'Accessory usage on production job',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-057',
    nextId: 'LC100-059',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/accessoryFulfillment.test.js' },
  },
  {
    id: 'LC100-059',
    title: 'Stone flatsheet production usage',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-058',
    nextId: 'LC100-060',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S10' },
    mapsTo: 'S10',
  },
  {
    id: 'LC100-060',
    title: 'Production job cancel → refund eligibility',
    modules: ['production', 'refund'],
    type: 'integration',
    prevId: 'LC100-059',
    nextId: 'LC100-061',
    riskTags: [],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'Cancelled production job' },
  },
  {
    id: 'LC100-061',
    title: 'Completion adjustment after job done',
    modules: ['production'],
    type: 'integration',
    prevId: 'LC100-060',
    nextId: 'LC100-062',
    riskTags: ['dual_control'],
    runner: { kind: 'vitest', file: 'server/editApproval.test.js' },
  },
  {
    id: 'LC100-062',
    title: 'Recalculate stock after production correction',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-061',
    nextId: 'LC100-063',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/productionJobStockRecalc.test.js' },
  },
  {
    id: 'LC100-063',
    title: 'Offcut pool issue on production',
    modules: ['production', 'stock'],
    type: 'inventory',
    prevId: 'LC100-062',
    nextId: 'LC100-064',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/coilProductionBook.test.js' },
  },
  {
    id: 'LC100-064',
    title: 'E2E production register modal',
    modules: ['production', 'cutting_list'],
    type: 'e2e',
    prevId: 'LC100-063',
    nextId: 'LC100-065',
    riskTags: [],
    runner: { kind: 'e2e', spec: 'e2e/production-register.spec.js' },
  },
  {
    id: 'LC100-065',
    title: 'Material incident → refund link',
    modules: ['production', 'stock', 'refund'],
    type: 'integration',
    prevId: 'LC100-064',
    nextId: 'LC100-066',
    riskTags: ['financial_failure', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/materialIncidentCoilDamage.test.js' },
  },

  // ── STOCK (066–075) ───────────────────────────────────────────────────────
  {
    id: 'LC100-066',
    title: 'GRN: coil remaining + COIL-ALU stock increase',
    modules: ['stock'],
    type: 'smoke',
    prevId: 'LC100-065',
    nextId: 'LC100-067',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S1' },
    mapsTo: 'S1',
  },
  {
    id: 'LC100-067',
    title: 'GRN over-delivery allowed on PO line',
    modules: ['stock'],
    type: 'integration',
    prevId: 'LC100-066',
    nextId: 'LC100-068',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S1b' },
    mapsTo: 'S1b',
  },
  {
    id: 'LC100-068',
    title: 'Coil split: total kg unchanged',
    modules: ['stock'],
    type: 'inventory',
    prevId: 'LC100-067',
    nextId: 'LC100-069',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S3' },
    mapsTo: 'S3',
  },
  {
    id: 'LC100-069',
    title: 'Reserved mass blocks over-split (integrity guard)',
    modules: ['stock', 'production'],
    type: 'fraud',
    prevId: 'LC100-068',
    nextId: 'LC100-070',
    riskTags: ['fraud', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S5' },
    mapsTo: 'S5',
  },
  {
    id: 'LC100-070',
    title: 'WIP transfer + finished goods receipt',
    modules: ['stock', 'production'],
    type: 'inventory',
    prevId: 'LC100-069',
    nextId: 'LC100-071',
    riskTags: ['inventory_gap', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S7' },
    mapsTo: 'S7',
  },
  {
    id: 'LC100-071',
    title: 'Stone PO + GRN stock metres up',
    modules: ['stock'],
    type: 'integration',
    prevId: 'LC100-070',
    nextId: 'LC100-072',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S8' },
    mapsTo: 'S8',
  },
  {
    id: 'LC100-072',
    title: 'Accessory PO + GRN stock units up',
    modules: ['stock'],
    type: 'integration',
    prevId: 'LC100-071',
    nextId: 'LC100-073',
    riskTags: ['inventory_gap'],
    runner: { kind: 'vitest', file: 'server/inventoryScenarios.test.js', anchor: 'S9' },
    mapsTo: 'S9',
  },
  {
    id: 'LC100-073',
    title: 'Manual stock adjustment audit trail',
    modules: ['stock'],
    type: 'integration',
    prevId: 'LC100-072',
    nextId: 'LC100-074',
    riskTags: ['fraud', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/stockMovementOps.test.js' },
  },
  {
    id: 'LC100-074',
    title: 'Branch inventory isolation',
    modules: ['stock'],
    type: 'fraud',
    prevId: 'LC100-073',
    nextId: 'LC100-075',
    riskTags: ['fraud', 'branch_scope'],
    runner: { kind: 'vitest', file: 'server/productBranchInventory.test.js' },
  },
  {
    id: 'LC100-075',
    title: 'Month-end stock register 7-step workflow',
    modules: ['stock'],
    type: 'e2e',
    prevId: 'LC100-074',
    nextId: 'LC100-076',
    riskTags: ['dual_control', 'inventory_gap'],
    runner: { kind: 'e2e', spec: 'e2e/complete-gate.spec.js', grep: 'Store' },
  },

  // ── REFUND (076–085) ──────────────────────────────────────────────────────
  {
    id: 'LC100-076',
    title: 'Refund preview: overpayment detection',
    modules: ['refund', 'payment'],
    type: 'financial',
    prevId: 'LC100-075',
    nextId: 'LC100-077',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'overpayment detection' },
  },
  {
    id: 'LC100-077',
    title: 'Refund preview: unproduced metre detection',
    modules: ['refund', 'production', 'cutting_list'],
    type: 'financial',
    prevId: 'LC100-076',
    nextId: 'LC100-078',
    riskTags: ['financial_failure', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'unproduced meter' },
  },
  {
    id: 'LC100-078',
    title: 'Duplicate refund same category blocked',
    modules: ['refund'],
    type: 'fraud',
    prevId: 'LC100-077',
    nextId: 'LC100-079',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'duplicate refund' },
  },
  {
    id: 'LC100-079',
    title: 'Refund line exceeds category max rejected',
    modules: ['refund'],
    type: 'fraud',
    prevId: 'LC100-078',
    nextId: 'LC100-080',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'exceeds system-calculated' },
  },
  {
    id: 'LC100-080',
    title: 'Refund amount must match calculation lines sum',
    modules: ['refund'],
    type: 'fraud',
    prevId: 'LC100-079',
    nextId: 'LC100-081',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'does not match sum' },
  },
  {
    id: 'LC100-081',
    title: 'Requester cannot approve own refund',
    modules: ['refund'],
    type: 'fraud',
    prevId: 'LC100-080',
    nextId: 'LC100-082',
    riskTags: ['fraud', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'own refund request' },
  },
  {
    id: 'LC100-082',
    title: 'Approver cannot pay same refund (dual control)',
    modules: ['refund', 'payment'],
    type: 'fraud',
    prevId: 'LC100-081',
    nextId: 'LC100-083',
    riskTags: ['fraud', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'ENFORCE_DUAL_CONTROL' },
  },
  {
    id: 'LC100-083',
    title: 'Refund intelligence data quality flags',
    modules: ['refund', 'production'],
    type: 'integration',
    prevId: 'LC100-082',
    nextId: 'LC100-084',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'dataQualityIssues' },
  },
  {
    id: 'LC100-084',
    title: 'Full refund E2E: request → approve → pay',
    modules: ['refund', 'payment'],
    type: 'e2e',
    prevId: 'LC100-083',
    nextId: 'LC100-085',
    riskTags: ['dual_control'],
    runner: { kind: 'e2e', spec: 'e2e/sales-refund-finance-checklist.spec.js' },
  },
  {
    id: 'LC100-085',
    title: 'Refund production alignment warnings',
    modules: ['refund', 'production', 'cutting_list'],
    type: 'integration',
    prevId: 'LC100-084',
    nextId: 'LC100-086',
    riskTags: ['financial_failure', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/refundProductionAlignment.test.js' },
  },

  // ── FRAUD / SECURITY (086–095) ────────────────────────────────────────────
  {
    id: 'LC100-086',
    title: 'Unauthenticated API returns 401',
    modules: ['auth'],
    type: 'fraud',
    prevId: 'LC100-085',
    nextId: 'LC100-087',
    riskTags: ['hack'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-087',
    title: 'CSRF token required on ledger POST',
    modules: ['auth', 'payment'],
    type: 'fraud',
    prevId: 'LC100-086',
    nextId: 'LC100-088',
    riskTags: ['hack'],
    runner: { kind: 'vitest', file: 'server/csrfEnforcement.test.js' },
  },
  {
    id: 'LC100-088',
    title: 'Sales staff cannot pay refunds',
    modules: ['auth', 'refund'],
    type: 'fraud',
    prevId: 'LC100-087',
    nextId: 'LC100-089',
    riskTags: ['hack', 'dual_control'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-089',
    title: 'Cashier cannot approve refunds',
    modules: ['auth', 'refund'],
    type: 'fraud',
    prevId: 'LC100-088',
    nextId: 'LC100-090',
    riskTags: ['hack', 'dual_control'],
    runner: { kind: 'vitest', file: 'server/refundSecurity.test.js', anchor: 'cashier from approving' },
  },
  {
    id: 'LC100-090',
    title: 'Cross-branch quotation access blocked',
    modules: ['auth', 'quotation'],
    type: 'fraud',
    prevId: 'LC100-089',
    nextId: 'LC100-091',
    riskTags: ['hack', 'branch_scope'],
    runner: { kind: 'inline' },
  },
  {
    id: 'LC100-091',
    title: 'Rate limit on rapid ledger posts',
    modules: ['auth', 'payment'],
    type: 'fraud',
    prevId: 'LC100-090',
    nextId: 'LC100-092',
    riskTags: ['hack', 'fraud'],
    runner: { kind: 'vitest', file: 'server/rateLimit.test.js' },
  },
  {
    id: 'LC100-092',
    title: 'Idempotency key prevents duplicate receipt',
    modules: ['payment'],
    type: 'fraud',
    prevId: 'LC100-091',
    nextId: 'LC100-093',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/idempotency.test.js' },
  },
  {
    id: 'LC100-093',
    title: 'Login lockout after failed attempts',
    modules: ['auth'],
    type: 'fraud',
    prevId: 'LC100-092',
    nextId: 'LC100-094',
    riskTags: ['hack'],
    runner: { kind: 'vitest', file: 'server/loginSecurity.test.js' },
  },
  {
    id: 'LC100-094',
    title: 'RBAC: procurement cannot access finance ledger',
    modules: ['auth', 'payment'],
    type: 'fraud',
    prevId: 'LC100-093',
    nextId: 'LC100-095',
    riskTags: ['hack'],
    runner: { kind: 'e2e', spec: 'e2e/access-control.spec.js' },
  },
  {
    id: 'LC100-095',
    title: 'Refund hard cap vs quotation cash-in',
    modules: ['refund', 'payment'],
    type: 'fraud',
    prevId: 'LC100-094',
    nextId: 'LC100-096',
    riskTags: ['fraud', 'financial_failure'],
    runner: { kind: 'vitest', file: 'server/refundFinancialGuards.test.js' },
  },

  // ── CRASH / HARSH (096–100) ───────────────────────────────────────────────
  {
    id: 'LC100-096',
    title: '114-scenario matrix full batch (stress)',
    modules: ['quotation', 'payment', 'cutting_list', 'production', 'refund'],
    type: 'crash',
    prevId: 'LC100-095',
    nextId: 'LC100-097',
    riskTags: ['financial_failure', 'inventory_gap'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js' },
    mapsTo: 'SCN-001–SCN-HARSH-08',
  },
  {
    id: 'LC100-097',
    title: 'Four-way treasury split payment request payout',
    modules: ['payment'],
    type: 'crash',
    prevId: 'LC100-096',
    nextId: 'LC100-098',
    riskTags: ['financial_failure'],
    runner: { kind: 'vitest', file: 'server/scenarioMatrix.test.js', anchor: 'SCN-HARSH-07' },
    mapsTo: 'SCN-HARSH-07',
  },
  {
    id: 'LC100-098',
    title: 'Concurrent bootstrap + ledger read under load',
    modules: ['payment', 'quotation'],
    type: 'crash',
    prevId: 'LC100-097',
    nextId: 'LC100-099',
    riskTags: [],
    runner: { kind: 'vitest', file: 'scripts/load-test-100vus-5min.mjs' },
  },
  {
    id: 'LC100-099',
    title: 'Complete SOP gate: sales + finance + operations roles',
    modules: ['quotation', 'payment', 'cutting_list', 'production', 'stock', 'refund'],
    type: 'e2e',
    prevId: 'LC100-098',
    nextId: 'LC100-100',
    riskTags: ['dual_control'],
    runner: { kind: 'e2e', spec: 'e2e/complete-gate.spec.js' },
  },
  {
    id: 'LC100-100',
    title: 'Master chain integrity: all 100 scenarios linked end-to-end',
    modules: ['quotation', 'payment', 'cutting_list', 'production', 'stock', 'refund'],
    type: 'integration',
    prevId: 'LC100-099',
    nextId: null,
    riskTags: [],
    runner: { kind: 'inline' },
  },
];

export const LIFECYCLE_100_COUNT = CORE_LIFECYCLE_100.length;

/** @param {string} id */
export function getLifecycleScenario(id) {
  return CORE_LIFECYCLE_100.find((s) => s.id === id) || null;
}

/** Validate chain links: exactly 100 scenarios, single chain from 001 to 100. */
export function validateLifecycle100Chain() {
  const errors = [];
  if (CORE_LIFECYCLE_100.length !== 100) {
    errors.push(`Expected 100 scenarios, got ${CORE_LIFECYCLE_100.length}`);
  }
  const ids = new Set(CORE_LIFECYCLE_100.map((s) => s.id));
  if (ids.size !== CORE_LIFECYCLE_100.length) {
    errors.push('Duplicate scenario ids detected');
  }
  const first = CORE_LIFECYCLE_100[0];
  if (first?.prevId !== null) errors.push('LC100-001 must have prevId null');
  const last = CORE_LIFECYCLE_100[99];
  if (last?.nextId !== null) errors.push('LC100-100 must have nextId null');
  for (const s of CORE_LIFECYCLE_100) {
    if (s.prevId && !ids.has(s.prevId)) errors.push(`${s.id}: missing prevId ${s.prevId}`);
    if (s.nextId && !ids.has(s.nextId)) errors.push(`${s.id}: missing nextId ${s.nextId}`);
    if (s.prevId) {
      const prev = getLifecycleScenario(s.prevId);
      if (prev?.nextId !== s.id) errors.push(`${s.id}: prev ${s.prevId} does not point back`);
    }
    if (s.nextId) {
      const next = getLifecycleScenario(s.nextId);
      if (next?.prevId !== s.id) errors.push(`${s.id}: next ${s.nextId} does not point back`);
    }
  }
  return { ok: errors.length === 0, errors };
}

/** Group scenarios by type for selective test runs. */
export function scenariosByType(type) {
  return CORE_LIFECYCLE_100.filter((s) => s.type === type);
}

/** Group scenarios by risk tag. */
export function scenariosByRisk(tag) {
  return CORE_LIFECYCLE_100.filter((s) => s.riskTags.includes(tag));
}

/** All inline scenarios that need direct API tests in coreLifecycle100.test.js */
export function inlineScenarioIds() {
  return CORE_LIFECYCLE_100.filter((s) => s.runner.kind === 'inline').map((s) => s.id);
}
