#!/usr/bin/env python3
"""Merge Zarewa project markdown docs into one file (excludes node_modules, build artifacts)."""
from pathlib import Path

ROOTS = [
    Path(r"C:\Users\USER\OneDrive\Desktop\Zarewa-backend-main"),
    Path(r"C:\Users\USER\OneDrive\Desktop\Zarewa-frontend-main"),
]

OUT = Path(r"C:\Users\USER\OneDrive\Desktop\Zarewa-backend-main\docs\ZAREWA_COMPLETE_DOCUMENTATION.md")

SKIP_DIR_NAMES = {
    "node_modules",
    ".git",
    ".build",
    "dist",
    "build",
    ".next",
    "coverage",
    ".cache",
    "playwright-report",
    "test-results",
}

PRIORITY = {
    "README.md": 0,
    "docs/OPERATIONS_MANUAL.md": 1,
}


def should_skip(path: Path) -> bool:
    if path.resolve() == OUT.resolve():
        return True
    return any(part in SKIP_DIR_NAMES for part in path.parts)


def collect_files():
    seen = set()
    files = []
    for root in ROOTS:
        if not root.is_dir():
            continue
        for path in root.rglob("*.md"):
            if should_skip(path):
                continue
            key = str(path.resolve()).lower()
            if key in seen:
                continue
            seen.add(key)
            rel = str(path.relative_to(root)).replace("\\", "/")
            files.append((root.name, rel, path))
    return files


def main():
    files = collect_files()

    def sort_key(item):
        repo, rel, _ = item
        repo_order = 0 if "backend" in repo.lower() else 1
        pri = PRIORITY.get(rel, 99)
        return (repo_order, pri, rel.lower())

    files.sort(key=sort_key)

    lines = [
        "# Zarewa — Complete Documentation (Consolidated)",
        "",
        "> Auto-generated consolidation of project markdown from Zarewa-backend and Zarewa-frontend.",
        "> Do not edit this file directly — update source documents and re-run `scripts/consolidate-docs.py`.",
        "",
        f"**Generated:** 2026-06-07  |  **Sources:** {len(files)} files",
        "",
        "---",
        "",
        "## Table of contents",
        "",
    ]

    for i, (repo, rel, _) in enumerate(files, 1):
        anchor = rel.replace("/", "-").replace(".", "").lower()
        lines.append(f"{i}. [{repo}/{rel}](#{anchor})")

    lines.extend(["", "---", ""])

    for repo, rel, path in files:
        anchor = rel.replace("/", "-").replace(".", "").lower()
        content = path.read_text(encoding="utf-8", errors="replace")
        lines.extend(
            [
                f'<a id="{anchor}"></a>',
                "",
                f"# Source: `{repo}/{rel}`",
                "",
                content.rstrip(),
                "",
                "",
                "---",
                "",
            ]
        )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"Files: {len(files)}")
    print(f"Size: {OUT.stat().st_size:,} bytes ({OUT.stat().st_size / 1024 / 1024:.1f} MB)")


if __name__ == "__main__":
    main()
